title: "LibreWP"
description: "Empower your projects with a cutting-edge, community-driven, open-source content management system evolved from WordPress."
status: "In Active Development"

author-name: "i am Programmer"
author-url: "https://iamprogrammer.lk"
github-url: "https://github.com/librewp"
x-url: "https://x.com/librewp"
linkedin-url: "https://linkedin.com/company/librewp"
email: "librewp@iamprogrammer.lk"
